### ISSUE TITLE
rust-hpke by default?

### ISSUE THREAD

**Issue by rillian** [martinthomson/ohttp#22]
Hi! Thanks for sharing this implementation.

Given the extra steps needed to build the nss library, is there a reason not to use the native rust implementation by default?

**Comment by martinthomson** [comment]
I stupidly did this myself at basically the same time as you, sorry about that.

Let me know if I fouled anything up.

**Comment by rillian** [comment]
No worries, seems to work fine here. Nice to see versioned crates published!
