### ISSUE TITLE
bhttp: Mode::IndefiniteLength

### ISSUE THREAD

**Issue by LPardue** [martinthomson/ohttp#41]
I think this got renamed to `Indeterminate` at some point before RFC 9292 was cut. Its a close match but might confuse folks switching between modes.

**Comment by martinthomson** [comment]
Reasonable, and easy to fix.

I've added an alias for the command-line, but I don't see the same option for the Enum.  A ["major" revision](https://doc.rust-lang.org/cargo/reference/resolver.html#semver-compatibility) (0.3.x -> 0.4.x) should ensure that dependent code doesn't get hit with a surprise.
