### ISSUE TITLE
ohttp-client config deserialization fails for hpke build

### ISSUE THREAD

**Issue by DanGould** [martinthomson/ohttp#52]
In testing how OHTTP applies to an application I'm working on I came across this implementation but have had no luck getting a client-server connection yet. Tests pass on main ([fc3f4c7](https://github.com/martinthomson/ohttp/commit/fc3f4c787d1f6a6a87bf5194f7152cc906b02973)) and tag v0.4.0, ohttp-sever runs properly, but ohttp-client fails following the [readme](https://github.com/martinthomson/ohttp/tree/main/ohttp-server#readme) with the following:

```console
Running `target/debug/ohttp-client --trust ./ohttp-server/ca.crt 'https://localhost:9443/' -i ./examples/request.txt 
000020b5054ad7410f396e55650af612fb54d4d6b9958181fe54a12bfc6f2d8fea571800080001000100010003
Error: Io(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })
```

I've tracked this down to an issue with the following line in `decode_list`, specifically `usize::from(r.read_u16::<NetworkEndian>()?);` always seems to evaluate to `0` in the following lines.

https://github.com/martinthomson/ohttp/blob/fc3f4c787d1f6a6a87bf5194f7152cc906b02973/ohttp/src/lib.rs#L243-L252

@notmandatory was also able to replicate

I'm running rust version cargo 1.70.0 (ec8a8a0ca 2023-04-25) on intel macOS 13.4.1

**Comment by martinthomson** [comment]
I see what is going on here.  The server prints a single item, where it should be printing a list.  Your pull request goes the other way, which isn't really what was intended.  Give me a few minutes.

**Comment by martinthomson** [comment]
OK, the refactoring took a little longer than I might have liked, but it should be fixed now.

**Comment by DanGould** [comment]
Tested as fixed. Parsing a list does seem to be in more of a spirit of OHTTP so the fix makes sense to me. Thank you.
