### ISSUE TITLE
MSRV for crate

### ISSUE THREAD

**Issue by jbesraa** [martinthomson/ohttp#57]
latest release `0.5.0` is at `1.65` as it uses `let-else` https://doc.rust-lang.org/rust-by-example/flow_control/let_else.html
specifically here: https://github.com/martinthomson/ohttp/commit/a25a42d5f0d381ec4ec985ecd7b081912461eb78

we are trying to maintain MSRV `1.63`  at https://github.com/payjoin/rust-payjoin and would be thankful if u could revert that commit?

**Comment by jbesraa** [comment]
@martinthomson happy to create a PR if its ok with you

**Comment by DanGould** [comment]
I confirm that this builds on 1.63.0 with a commit with this change https://github.com/martinthomson/ohttp/commit/ce452e19454ab31598243486526fcd82c6567672

**Comment by martinthomson** [comment]
Sorry about that.  I've been doing let-else assignments for so long I forgot that it is still relatively new.  Reverted and 0.5.1 released for you.

**Comment by martinthomson** [comment]
As for MSRV, I will open a bug so that we can test on a matrix and keep a reasonable MSRV.
