### ISSUE TITLE
Test MSRV in CI

### ISSUE THREAD

**Issue by martinthomson** [martinthomson/ohttp#59]
Other projects use a matrix arrangement in their workflow file to ensure that the code continues to work on a set minimum rust version.  Do that.  We have a request for 1.63 as a minimum, though the actual minimum is probably lower right now.  Work out what it is and make CI enforce that, so that any change to MSRV is deliberate.

**Comment by DanGould** [comment]
It turns out our MSRV is indeed 1.63 since our dependency [`socket2-0.5.3`'s is](https://github.com/rust-lang/socket2#minimum-supported-rust-version-msrv)
