### ISSUE TITLE
Implement Clone for ClientResponse

### ISSUE THREAD

**Issue by BitcoinZavior** [martinthomson/ohttp#60]
**Title**: Implement `Clone` Trait in `ClientResponse` Struct for FFI Compatibility in `rust-payjoin`

### Overview
We are currently developing [Payjoin-FFI](https://github.com/LtbLightning/payjoin-ffi) (Foreign Function Interface) code for the [rust-payjoin](https://github.com/payjoin/rust-payjoin) project. Our goal is to enable bindings for Python, Kotlin, and Swift. This effort involves using the [uniffi-rs](https://github.com/mozilla/uniffi-rs) crate from Mozilla.

### Issue Description
In the `rust-payjoin` project, the `ClientResponse` struct from the `ohttp` crate is a crucial component and used in various functions. However, we have encountered a significant obstacle: the `ClientResponse` struct does not implement the `Clone` trait. This absence hinders our ability to work efficiently with these functions in our FFI code.

### Requested Change
Implementing the `Clone` trait for the `ClientResponse` struct would be highly beneficial. With this trait in place, we would be able to utilize the `ClientResponse` struct more flexibly and effectively in our FFI implementations. This enhancement would not only simplify our code but also improve its overall cleanliness and maintainability.

### Impact
The addition of the `Clone` trait to the `ClientResponse` struct is a critical step towards achieving seamless integration across multiple programming languages. It will enable us to create more robust and versatile FFI code, significantly benefiting the broader `rust-payjoin` user community.

**Comment by martinthomson** [comment]
`ClientResponse` is deliberately not cloneable.  Cloning it would create a potential vulnerability in the sense that it would allow two different payloads to be decrypted with the same AEAD keys through the `decapsulate` function.  That doesn't directly create a problem - something would still need to produce the ciphertexts - but it takes a big step toward problems that are very bad for the integrity of the protocol[^1].

[^1]: If two different inputs are encrypted under the same key and nonce, the key can be recovered.

**Comment by BitcoinZavior** [comment]
@martinthomson 
I see, we might implement Serialize and deserialize in the payjoin structs that has ClientResponse and save the variables as a string in our payjoin-ffi code. if this doesn't work, we might need to implement Serialize and deserialize for ClientReponse in ohttp.

**Comment by martinthomson** [comment]
Yes, if you need to save and recover these structs, you really are on your own.  I would still not advise persistence for these structures because of the risk that you might use them twice.  Of course, if you are willing to take that risk on, then that's something that you will need to think on.

If you do want the ability to save state like that, I'd consider taking a patch, but only on the basis that it would be behind an optional feature flag.  After all, serialize/deserialize as a workaround for not having `Clone` is no safer than implementing `Clone` directly.
